requirements.txt

This adds support for the latest schema changes.

SOLR-27: Update mbdata requirement

---

sir/schema/__init__.py
sir/schema/modelext.py
sir/schema/queryext.py
sir/trigger_generation/__init__.py
sir/trigger_generation/types.py
test/test_trigger_generation.py

I'm currently in a process of figuring out how trigger generation works. Been updating documentation and making some other improvements to that code as I go along.

Trigger generator improvements (docs and code cleanup)

---

.gitignore
sir/__main__.py
sir/indexing.py

Tried to keep to the style settings (although I hate the 80-character line length limit).
I'm still not sure why the imports are apparently not an issue for you, but break things on my end. Instead of fully reverting commit 1fab3aa9cb2d0be4bf6e8dec5391704055394014 I modified one import at a time until a reindex operation (using instruments since that's a small dataset) succeeded. Looks like it's only __main__.py that needs relative imports.

Small fixes

---

config.ini.ctmpl
requirements.txt
sir/amqp/handler.py
sir/amqp/message.py
sir/schema/__init__.py
sir/schema/modelext.py
sir/trigger_generation/__init__.py
sir/trigger_generation/paths.py
sir/trigger_generation/sql_generator.py
sql/CreateFunctions.sql
sql/CreateTriggers.sql
test/test_amqp_handler.py
test/test_amqp_message.py

SOLR-40: Handling of the new message format

---

sir/wscompat/convert.py

This seems to fix the issue. https://chatlogs.metabrainz.org/brainzbot/metabrainz/2017-07-09/?msg=3948244&page=1

SOLR-44: Handle new types of models correctly

---

sir/wscompat/convert.py

Fixes https://tickets.metabrainz.org/browse/SOLR-52 and https://tickets.metabrainz.org/browse/SOLR-50

SOLR-52, SOLR-50: Fix indexing for Work entity

---

sir/schema/__init__.py
sir/schema/modelext.py
sir/wscompat/convert.py

 SOLR-5, SOLR-15, SOLR-56, SOLR-58: Bring Work to current search parity

---

sir/wscompat/convert.py
test/test_wscompat_convert.py

See https://tickets.metabrainz.org/browse/SOLR-61 for the list of errors

SOLR-61: Bring Recording to search parity

---

docs/source/api/triggers.rst
docs/source/conf.py
sir/__init__.py

See individual commits for changes.

Fix documentation generation

---

sir/amqp/handler.py
sir/schema/__init__.py
sir/trigger_generation/__init__.py
sir/trigger_generation/sql_generator.py
sql/CreateFunctions.sql
sql/CreateTriggers.sql
test/test_amqp_handler.py
test/test_querying.py

Fixes https://tickets.metabrainz.org/browse/SOLR-77

SOLR-77: Fix the way FK rels were handled

---

config.ini.ctmpl
sir/amqp/handler.py
sir/amqp/message.py
sir/indexing.py
sir/schema/__init__.py
sir/trigger_generation/paths.py
sir/util.py
test/test_amqp_handler.py
test/test_amqp_message.py

Learnt the hard way that it's an absolute headache combining threads and multiprocessing. Converted the scheduled call to process events to a normal call by making drain events time out. 
Fixes:
https://tickets.metabrainz.org/browse/SOLR-72 
https://tickets.metabrainz.org/browse/SOLR-73 
https://tickets.metabrainz.org/browse/SOLR-74

SOLR-72, SOLR-73, SOLR-74: Non-threaded multiprocessed import

---

sir/schema/__init__.py
sir/schema/modelext.py
sir/wscompat/convert.py
sql/CreateFunctions.sql
sql/CreateTriggers.sql

* This is a…
* JIRA ticket (_optional_): [SOLR-82](https://tickets.metabrainz.org/browse/SOLR-82)

Add release links to URL search

---

sir/schema/__init__.py
sir/schema/searchentities.py
sir/trigger_generation/__init__.py

Add refcount to artist index

---

sir/schema/__init__.py
sir/schema/modelext.py

Add ref_counts for areas based on places and labels

---

sir/schema/__init__.py

Add instrument names to the index

---

sir/schema/__init__.py
sir/schema/modelext.py

Add release counts for labels

---

sir/schema/__init__.py
sir/schema/modelext.py

Add recording counts to Works

---

sir/amqp/handler.py
sir/indexing.py
sir/schema/__init__.py
sir/trigger_generation/paths.py

Update copyright headers with appropriate attribution

---

config.ini.ctmpl

Update consul template to allow Sir to be run under different DEPLOY ENV

---

sir/indexing.py

Add multiple consumers

---

config.ini.ctmpl

Use a custom solr URI instead of pointing to the service

---

GenerateDropSql.pl

Add script to generate drop triggers

---

sir/schema/__init__.py

See https://github.com/metabrainz/mbsssss/pull/41 for explanation
* This is a…

Rename fields which are posted to Solr

---

sir/wscompat/convert.py

* This is a…
* JIRA ticket (_optional_): [SOLR-92](https://tickets.metabrainz.org/browse/SOLR-92)

SOLR-92: Fix compat issues with WS

---

sir/schema/__init__.py
sir/schema/modelext.py
sir/schema/searchentities.py
sql/CreateTriggers.sql

* This is a…
* JIRA ticket (_optional_): [SOLR-91](https://tickets.metabrainz.org/browse/SOLR-91)
Depends on https://github.com/metabrainz/mbsssss/pull/49

SOLR-91: Add a primary alias field to allow for independent boosting for them

---

test/test_wscompat_convert.py

* This is a…
This works and makes sure we test with the types the real code is going to use.

Use mbdata.models types instead of mocks for tests

---

sir/schema/__init__.py
sir/wscompat/convert.py

SEARCH-624: status-id is missing in Search Server JSON results
* Use release status `gid` along with its name when converting status object.
* Add `status.id` as not-searchable field in `extrapaths` for `SearchRecording`, `SearchRelease`, and `SearchReleaseGroup`.
* https://wiki.musicbrainz.org/index.php?title=MusicBrainz_API/Search/RecordingXmlOutput&diff=74971&oldid=74556
* https://wiki.musicbrainz.org/index.php?title=MusicBrainz_API/Search/RecordingJsonOutput&diff=74972&oldid=74552
* https://wiki.musicbrainz.org/index.php?title=MusicBrainz_API/Search/ReleaseXmlOutput&diff=74973&oldid=74572
* https://wiki.musicbrainz.org/index.php?title=MusicBrainz_API/Search/ReleaseJsonOutput&diff=74974&oldid=74568
1. Merge metabrainz/mb-solr#41 too.
2. Release both PRs at the same time.
3. Make …

SEARCH-624 (indexer): Add id to release status

---

requirements.txt
sir/__init__.py
sir/__main__.py
sir/amqp/handler.py
sir/indexing.py

sentry-sdk is the new python sdk for sentry. We have already upgraded to it in many other *Brainz projects (LB, CB, AB and MeB). The changes here are in line with those discussed here: https://github.com/metabrainz/brainzutils-python/pull/56

Upgrade raven -> sentry-sdk

---

config.test.ini
docker/Dockerfile.test
docker/docker-compose.test.yml
sir/indexing.py
sir/querying.py
sir/util.py
test.sh
test/sql/annotation.sql
test/sql/area.sql
test/sql/artist.sql
test/sql/cdstub.sql
test/sql/editor.sql
test/sql/event.sql
test/sql/instrument.sql
test/sql/label.sql
test/sql/place.sql
test/sql/recording.sql
test/sql/release-group.sql
test/sql/release.sql
test/sql/series.sql
test/sql/tag.sql
test/sql/url.sql
test/sql/work.sql
test/test_indexing_real_data.py

1) Setup musicbrainz test database for use in tests
2) Fix some warnings encountered in tests
3) Add sql files for real data to use during tests - mostly borrowed from https://github.com/metabrainz/musicbrainz-server/tree/master/t/sql
4) Add tests checking messages output by indexer (currently only for area, will add more once the current one is approved).

Add indexing tests using real data

---

sir/wscompat/convert.py

See individual commit descriptions for detail.

Improve loading release-group, release and recording

---

sir/schema/__init__.py
sir/schema/modelext.py
sir/schema/transformfuncs.py
test/sql/work.sql
test/test_indexing_real_data.py

See individual commit messages for details.

Improve indexing works

---

RELEASING.md

Steps to release a new version of SIR. Similar to:
- https://github.com/metabrainz/picard/blob/master/RELEASING.md for Picard
- https://github.com/metabrainz/musicbrainz-server/blob/master/RELEASING.md for MusicBrainz Server
Details for deployment will be added separately.

Document releasing a new version, step-by-step

---

docs/source/conf.py
docs/source/setup/install.rst
setup.py
sir/sir.py
tox.ini

It follows the commit 9bbff6db37cfd5a371ca17b6e59ff0fc79e96891 I pushed to the `master` branch directly to regenerate SQL scripts.
It fixes a few oversights from the pull request #142 upgrading to Python 3.
See commit messages.

SEARCH-594 (fixes): Various fixes to the Python 3 upgrade

---

.github/workflows/ci.yml
docker/docker-compose.test.yml
test.sh

Move SIR tests from self-hosted Jenkins CI to Github Actions.

Move SIR tests to Github Actions

---

sir/amqp/handler.py

pysolr.delete requires the doc_id passed to it to be a string. Otherwise, its internal xml parsing code is unhappy (pysolr internally uses xml payloads for solr requests in many/most cases). Also, log the complete stacktrace in `callback_wrapper` to make debugging in case of failures easier.
For reference, one of the failing messages had the following stacktrace:
```
Traceback (most recent call last):
File "/usr/local/lib/python3.13/xml/etree/ElementTree.py", line 1014, in _escape_cdata
if "&" in text:
^^^^^^^^^^^
TypeError: argument of type 'int' is not iterable
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/code/sir/amqp/handler.py", line 122, in wrapper
f(self=self, parsed_message=parsed_message) …
```

doc_id for pysolr.delete should be a string

---

sir/schema/__init__.py
sir/schema/searchentities.py
test/helpers.py
test/models.py
test/test_querying.py

- Fix handling of column properties vs relationship properties
- Use raiseload to catch unintentional lazy loading
- Fix handling of composite properties (instead of part column names the part column property objects were being added which lead to incorrect deferring)
- Add medium.gid to eagerly loaded fields for recording (it is used by convert_medium_for_track)

Improve deferred loading
