metabrainz/sir

sir/wscompat/convert.py
The incoming data does not seem to include any links, so we cannot currently build any relation lists.
But then the solr documents also don't have the relationtype, targetid or targettype fields yet, so I guess that's to be expected.
=> SOLR-41: Added basic conversion for URLs.

sir/wscompat/convert.py
Example - 
The XML output (see tag list)
http://35.193.119.46:8983/solr/artist/select?&q=artist:Beatsteaks&wt=mbxml
The Json output
http://35.193.119.46:8983/solr/artist/select?&q=artist:Beatsteaks&wt=mbjson
How it is currently - 
http://musicbrainz.org/ws/2/artist/?query=artist:Beatsteaks
http://musicbrainz.org/ws/2/artist/?fmt=json&query=artist:Beatsteaks
=> SOLR-17: Remove tag count due to buggy JSON output

sir/schema/searchentities.py
It is a very crucial bug that needs to be fixed.
Because of this a lot of paths aren't indexed resulting in bad results or no results at all.
We could also probably revert this commit instead which results in a more readable code than the current PR- 
https://github.com/metabrainz/sir/commit/407797657ff4d57c51fec3e611c6b402e9a7680e#diff-567bd28acbaf93f59a1ad29b635e31a5
=> SOLR-62: Fix bug in path iteration of a field

sir/wscompat/convert.py
Most of the code for calculating release type is included in #40 
We will need to rebase this after merging #40
=> SOLR-63: Bring Release Group to current search parity

sir/amqp/handler.py, sir/amqp/message.py, sir/schema/__init__.py, sir/trigger_generation/__init__.py, sir/trigger_generation/paths.py, sir/trigger_generation/sql_generator.py, sir/trigger_generation/test/test_paths.py, sql/CreateFunctions.sql, test/test_amqp_handler.py
So currently when a non core entitiy is deleted, the currently `generate selection` tries to update all the related paths in `update_map` by creating a SQL query which is dependent on that particular deleted row being present eg - `select id from musicbrainz.area where musicbrainz.area.id in (select are from musicbrainz.area_alias where musicbrainz.area_alias.id in (:ids))` now the inner query returns nothing since those rows are deleted.
=> Fix live indexing selections

sir/schema/__init__.py
Ref count isn't used anywhere in the XML schema and including it in the
search schema caused the live indexer to reindex entities like VA
everytime their ref count increased. This meant reindex of 3 million+
documents. As such it was decided to remove this.
=> Remove ref_count from the schema

requirements.txt, sir/indexing.py, sir/schema/searchentities.py, sir/util.py, test/test_indexing.py, test/test_searchentities.py
* This is a…
Initial port to Py3. Since solrpy doesn't support py3.5+, we switch to pysolr. It also comes with its own benefit as we are able to take care of SOLR-33.
Port to py3 is essential for maintainability as py2 support stops in 2020. This also involves switching from solrpy to pysolr. pysolr also cleans control chars. before submitting to Solr so it should take care of SOLR-33.
* JIRA ticket: [SOLR-33](https://tickets.metabrainz.org/browse/SOLR-33)
Updated solrpy to pysolr. Since pysolr does not support sets as an iterable, I had to convert the values from sets to list before sending to solr. I made a patch upstream to solr @https://github.com/django-haystack/pysolr/pull/229. We can remove the typecast once it gets merged.
=> Initial port to Py3

sir/schema/__init__.py, sir/schema/modelext.py, sir/schema/transformfuncs.py
Basically improves count efficiency and adds artists into the mix, which weren't added earlier due to slow query for its return value to the search results.
* This is a…
=> Improve query efficiency when calculating ref_counts

sir/indexing.py, test/test_indexing.py
* This is a…
zas suggested we should have a failsafe in case post requests to Solr fail from sir side.
Currently it requeues the entire pending messages to the search.retry queue in case even a single Post fails.
=> Add pending messages to the retry queue in case any of them fails.

sir/schema/__init__.py, sir/schema/transformfuncs.py, sir/wscompat/convert.py
The current search fills in values for barcode when its empty or [none] and doesn't differentiate in search between [none] and an unset value. This patch fixes that and allows searching for `barcode:none` to find [none] type barcodes and `-barcode:*` to find barcodes with no value set.
* This is a…
=> Fix barcode compat issues

sir/wscompat/convert.py
The following applies to the notation of the release group entity type in annotation search only.
Old search server used to return `release_group` as specified in the file [entities.json](https://github.com/metabrainz/musicbrainz-server/blob/master/entities.json), whereas the new search server returns `releasegroup` thus confusing the MusicBrainz server ([MBS-9790](https://tickets.metabrainz.org/browse/MBS-9790)).
This one-line patch fixes that notation.
=> SOLR-97: Fix Release Group type for Annotation

docs/source/setup/install.rst, sir/__main__.py, sir/config.py
* This is a…
Configuring `sir` using environment variables required to modify the file `config.ini` on the fly.
Example use case: Setting PG password through environment at Docker Compose level.
Expand environment variables of the form `$NAME` and `${NAME}` in configuration values.
Besides, set program name to `sir` (instead of `__main__.py`) for usage message.
=> Expand environment variables in configuration values

requirements.txt
This fixes CVE-2018-18074 which could make it easier for remote attackers to discover sentry credentials by sniffing the network.
=> SEC-2: Update requests to 2.21.0 (latest)

sir/wscompat/convert.py, test/test_wscompat_convert.py
* This is a…
* JIRA ticket (_optional_): [MBS-9789](https://tickets.metabrainz.org/browse/MBS-9789)
The MusicBrainz server uses the results of a web service search to display recording info in the Recordings tab of the release editor. Because the artist credits returned by the web service do not include the credited name, the displayed data in the MusicBrainz release editor is inaccurate and (mostly harmful, but confusing) errors occur (see the linked ticket for details).
Readding the credited name for artist credits that was removed with 58487f12d7b442beb29b894a85bbf155cb0040ae
=> MBS-9789: Return the credited name for ACs

requirements.txt, searchfields.org, sir/wscompat/convert.py, test/test_wscompat_convert.py
Update to [MMD schema 2.0 used in production as of January 7th, 2019](https://github.com/metabrainz/mmd-schema/releases/tag/v-2019-01-07).
Changes in MMD schema and/or MB WS have not been followed by MB SOLR which no longer complies with MMD 2.0 schema.
Update the Python bindings for MMD schema to [mb-rngpy v-2.20190107.0](https://github.com/metabrainz/mb-rngpy/releases/tag/v-2.20190107.0).
Make relevant changes to follow https://github.com/metabrainz/mb-rngpy/pull/3 which includes:
* [MBS-8974](https://tickets.metabrainz.org/browse/MBS-8974): Add isni-list to artist & label.
:arrow_right: addressed with commit https://github.com/metabrainz/sir/commit/50db024a8a8b7e55eae9e7c592adf8535cf02bdf;
* [MBS-8978](https://tickets.metabrainz.org/browse/MBS-8978): Add packaging id attribute of type …
=> Update SIR to MMD schema 2.0 v-2019-01-07

requirements.txt, sir/indexing.py, sir/schema/searchentities.py, test/test_indexing.py, test/test_searchentities.py
No breaking changes:
* mbdata: follows non-disruptive schema change 25;
* pysolr: no longer commit by default, see [release tag v3.8.1](https://github.com/django-haystack/pysolr/releases/tag/v3.8.1);
Removed disabling auto-commit from `sir/indexing.py` since it is now disabled by default.
(Edit: no longer bump sqlalchemy to 1.3.3 as it [breaks tests](https://ci.metabrainz.org/job/sir/476/#showFailuresLink), should check [migration from 1.0](https://docs.sqlalchemy.org/en/11/changelog/migration_11.html), [from 1.1](https://docs.sqlalchemy.org/en/12/changelog/migration_12.html), and [from 1.2](https://docs.sqlalchemy.org/en/13/changelog/migration_13.html) again.)
=> Update requirements mbdata and pysolr

Dockerfile, docker/push.sh
Tag docker image with:
* git ref (most recent tag, or current commit, with dirty mark)
* deployment target (currently 'git2consul' in production)
Label docker image with:
* sir version derived from git ref
* metabrainz/python base image version
* build timestamp
It improves building and releasing metabrainz/sir docker image to docker hub.
Update docker-server-configs accordingly.
=> Add labels and tag to docker image

sir/indexing.py
Skip indexing entity on unwanted control character, rather than abort indexing the whole core.
XML incompatible strings abort reindexing annotation, recording, release, and url cores.
* JIRA ticket: [SOLR-113](https://tickets.metabrainz.org/browse/SOLR-113)
* Handling ValueError raised from row converter, so as to skip (and log) affected row only.
* Logging other exceptions at pool worker level, so as to provide more helpful details.
Search Indexes:
* Reindex release core then annotation, recording, and url cores.
MusicBrainz Server:
* Prevent invalid characters to be entered, see [MBS-9112](https://tickets.metabrainz.org/browse/MBS-9112).
MusicBrainz Database:
* Clean already entered data (this patch logs table name and id of each skipped row)
=> SOLR-113: Skip indexing entity on unwanted control character

docker/Dockerfile.test, requirements.txt, requirements_dev.txt, setup.py, sir/__main__.py, sir/amqp/message.py, sir/schema/transformfuncs.py, sir/util.py, test/test_amqp_handler.py, test/test_amqp_message.py
* This is a refactoring
* Modernize Python 2 code (`futurize --stage1`) and upgrade dependencies as much as possible.
* To prepare for Python 3 (SEARCH-594), Python 2 code must be modernized ([in-depth guide](http://python3porting.com/preparing.html)) and dependencies must be updated to avoid known incompatibilities with recent versions of Python 3. 
Upgrading most dependencies didn’t require any change to the code but:
* amqp: Since 2.0.0 `Connection.connect()` must be called, see [changelog](https://amqp.readthedocs.io/en/2.5.2/changelog.html).
* sqlalchemy: Upgrading to version 1.1/1.2/1.3 is not straightforward and will require a separate PR.
=> Modernize Python 2 code and update dependencies

sir/schema/__init__.py, sir/wscompat/convert.py, test/test_wscompat_convert.py
SEARCH-623: 'gender-id' is missing from JSON/XML artist search results
* Use gender `gid` along with its name when converting gender object.
* Add `gender.id` as not-searchable field in `extrapaths` for `SearchArtist`.
Artist examples given in [MusicBrainz API / Search](https://musicbrainz.org/doc/MusicBrainz_API/Search) have no gender set.
1. Merge metabrainz/mb-solr#40 too.
2. Release both PRs at the same time.
=> SEARCH-623 (indexer): Add id to artist gender

requirements.txt, searchfields.org, sir/schema/__init__.py, sir/wscompat/convert.py, sql/CreateFunctions.sql, sql/CreateTriggers.sql
SEARCH-218: Add first release date to the web service indexed search results for recordings
It follows MBS-1424.
This patch adds:
* `first-release-date` to the stored content of `recording` core;
* `firstreleasedate` (advanced) search field to `recording` core.
To make it work, it requires:
* MusicBrainz database with active schema 26 (not released yet), or at least having the table `recording_first_release_date`;
* A (development) version of `mbdata` that supports this table;
* A version of `mb-rngpy` that matches mmd-schema v-2020-11-12.
It goes with PRs metabrainz/mbsssss#54 and metabrainz/mb-solr#46.
* https://wiki.musicbrainz.org/index.php?title=MusicBrainz_API/Search/RecordingSearch&curid=6978&diff=74995&oldid=74554
* https://wiki.musicbrainz.org/index.php?title=MusicBrainz_API/Searc …
=> SEARCH-218 (indexer): Recording’s first release date

searchfields.org, sir/schema/__init__.py, sir/schema/modelext.py, sir/wscompat/convert.py, sql/CreateFunctions.sql, sql/CreateTriggers.sql
SEARCH-319: Add first release date to the *results* of indexed search for release-groups
SEARCH-384: Add first release date to the *fields* of indexed search for release-groups
* Add `first-release-date` to the stored content of `release-group` core.
* Add `firstreleasedate` (advanced) search field to `release-group` core.
It goes with PRs metabrainz/mbsssss#54 (and metabrainz/mb-solr#46).
* https://wiki.musicbrainz.org/index.php?title=MusicBrainz_API/Search/ReleaseGroupSearch&curid=6974&diff=74996&oldid=74564
* https://wiki.musicbrainz.org/index.php?title=MusicBrainz_API/Search/ReleaseGroupXmlOutput&curid=6975&diff=75001&oldid=74566
* https://wiki.musicbrainz.org/index.php?title=MusicBrainz_API/Search/ReleaseGroupJsonOutput&curid=10034&diff=75002&oldid=74562
1. Merge related PR …
=> SEARCH-319 / SEARCH-384 (indexer): Release group’s first release date

config.ini.ctmpl
SIR container cannot be set to use a different service name than `rabbitmq` for RabbitMQ.
This is needed to switch to another instance of RabbitMQ. It helps with migrating RabbitMQ without interruption.
Use `RABBITMQ_SERVICE` container environment variable if available, or fallback to the current `rabbitmq`.
=> Support RABBITMQ_SERVICE environment variable

searchfields.org, sir/schema/__init__.py, sir/schema/modelext.py, sql/CreateFunctions.sql, sql/CreateTriggers.sql
SEARCH-644: Remove unintented ordering attribute from series index
This pull request stops filling this search field.
It also has to be removed it from search schema, see metabrainz/mbsssss#58.
1. Deploy metabrainz/mbsssss#58
2. Deploy this pull request
3. Rebuild `series` search index
=> SEARCH-644 (indexer): Stop indexing ordering attribute for series

Dockerfile, docker/Dockerfile.test, docker/prod/consul-template.conf, docker/prod/indexer/indexer.service
- Image build was broken since the `jessie-pdpg` distribution of PostgreSQL has been discontinued.
- Not a showstopper but it also relied on an outdated base image and outdated dependencies.
- Last it was still using `apt-key` which is deprecated since 2021 for security reasons.
- Switch to the latest Docker base image for Python 2 at MetaBrainz: `2.7-20210517;
* Update the configuration of Consul Template to work with the version `0.25.2`;
* To actually unblock image build: Refer to `focal-pdpg` for PostgreSQL distribution;
- Update PostgreSQL client to the version `12` (already used by MusicBrainz Server);
- Replace using `apt-key` with `curl`/`gpg` to generate safer `sources.list`;
=> Fix image build and update some dependencies

sir/trigger_generation/sql_generator.py, sql/CreateTriggers.sql
SEARCH-609: SIR triggers do not work as intended when running a MusicBrainz Slave instance
On the primary database: Sometimes columns are unnecessarily updated without a change to the value; See MBS-12178; In turn, triggers send unnecessary messages to SIR.
On replicated databases: The replication process update all columns even though only a small number of those actually have a new value. In turn, triggers send unnecessary messages to SIR.
Compare old/new values of columns before sending any message.
The only exception is `place.coordinates` of type `POINT` which isn’t as straightforward to compare as other data types.
Thanks to @ta264 for implementing it and allowing to incorporate it upstream. I just fixed a pair of bugs.
1. On deployment of the next SIR release in production, update …
=> SEARCH-609: Triggers only fire message on data change

requirements.txt, sir/schema/modelext.py
To prepare sir for the schema change, we need to update mbdata version which is compatible with the schema change. Also, updated a model in SIR so that its compatible with the new mbdata version.
=> Update SIR for schema change 2022 q2

docs/source/index.rst, docs/source/service/index.rst, docs/source/service/rabbitmq.rst
Document how SIR is using RabbitMQ, for system administrators and anyone involved in SIR or RabbitMQ service maintenance.
=> SEARCH-675: Document using RabbitMQ

requirements_dev.txt, sir/amqp/handler.py, sir/schema/__init__.py, sir/trigger_generation/__init__.py, sir/util.py, test/models.py
After upgrading SIR to SQLAlchemy 1.4, some deprecation warnings came up.
1. SADeprecationWarning: Use .persist_selectable (deprecated since: 1.3) mapped_table class_mapper(entity.model).mapped_table.name
Fix is straightforward use .persist_selectable instead of .mapped_table as looking at following docs it only seems to have been renamed.
[.mapped_table](https://docs.sqlalchemy.org/en/12/orm/mapping_api.html?highlight=mapped_table#sqlalchemy.orm.Mapper.mapped_table) in SQLAlchemy 1.2
[.persist_selectable](https://docs.sqlalchemy.org/en/14/orm/mapping_api.html?highlight=mapped_table#sqlalchemy.orm.Mapper.persist_selectable) in SQLAlchemy 1.4
2. SADeprecationWarning: Calling URL() directly is deprecated and will be disabled in a future release.  The public constructor for URL is now the …
=> Fix deprecation warnings in SIR

sir/schema/modelext.py
A warningsfilter in `sir/model/modelext.py` was suppressing some warnings. Instead of suppressing, fix those. 
> SAWarning: relationship 'AreaTag.area' will copy column area.id to column area_tag.area, which conflicts with relationship(s):   'CustomArea.tags' (copies area.id to area_tag.area). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards. To silence this warning, add the parameter 'overlaps="tags"' to the 'AreaTag.area' relationship.
This particular warnings arises from `tags = …
=> Fix more SQLAlchemy related warnings

sir/schema/__init__.py
convert_release_group used as wscompat converter for release group core calls convert_alias as well which accesses alias.gid so eagerly load it.
=> Fix performance regression in indexing release group

sir/schema/__init__.py
convert_release used as wscompat converter for release core calls convert_artist_simple as well which accesses comment so eagerly load it.
convert_release used as wscompat converter for release core calls convert_release_packaging as well which accesses comment so eagerly load it.
=> Fix performance regression in release indexing

sir/schema/__init__.py
convert_artist calls convert_area_inner on the area that accesses these area.type.name and area.type.gid attributes so eagerly load these for performance.
=> Eagerly load area_type related attributes for artist core

sir/schema/__init__.py, test/sql/label.sql, test/test_indexing_real_data.py
convert_label used as wscompat converter for label core calls convert_area_inner as well which accesses area.begin_date, area.end_date, area.ended so eagerly load it.
Also, add one more test case where these fields aren't NULL.
=> Eagerly load area attributes in label indexing

docs/source/setup/solr.rst, requirements.txt
There has been a few security vulnerabilities in `requests` and `urllib3` dependencies resolved by new versions. Even though those vulnerabilities do not affect SIR in its current usage, it is preferable to keep following the latest versions.
* Bump urllib3 required version to 2.5.0
* Bump requests required version to 2.32.4
=> Update requests and urllib3 dependencies

Dockerfile, docker/Dockerfile.test
I was able to build the images fine after removing these. I guess everything has a wheel now except for ujson, which only requires build-essential.
There are no crontabs in the repo, so I removed cron. git isn't required either. If these are needed for some one-off sysadmin task in the future, they can always be installed manually.
=> Remove unused apt packages from the Dockerfiles
